### ISSUE TITLE
Can't see a installation guide

### ISSUE THREAD

**Issue by arenaitmx** [ysjn/vimium-simply-dark#2]
Hi there. Thanks a lot for the theme. I can't find an installation guide to get this theme installed. Would it be please possible to help me to install it?. Do I need to just copy-paste the .css or is there any other thing I have to do ?

**Comment by ysjn** [comment]
Hi @arenaitmx 
Yes, you just need to copy and paste the css in Vimium settings.

<img src="https://user-images.githubusercontent.com/6050882/91941872-ec7e3d80-ed34-11ea-8e03-4da187503e3c.png" width="800" />

**Comment by OmiChrome** [comment]
@ysjn can u add this to `readme.md` please?

**Comment by ysjn** [comment]
Sorry to fix this super late. But I've added installation guide to `README.md`. :+1: https://github.com/ysjn/vimium-simply-dark/pull/21
